//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public string MaCTHD { get; set; }
        public string MaHoaDon { get; set; }
        public string MaMon { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
