//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThucMon
    {
        public string MaCongThuc { get; set; }
        public string MaMon { get; set; }
        public string MaNguyenLieu { get; set; }
        public decimal SoLuongSuDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Mon Mon { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
