//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.CongThucMons = new HashSet<CongThucMon>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string MaDanhMuc { get; set; }
        public decimal DonGia { get; set; }
        public string DonViTinh { get; set; }
        public string TrangThai { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongThucMon> CongThucMons { get; set; }
        public virtual DanhMucMon DanhMucMon { get; set; }
    }
}
